[package]
name = "audio_streaming_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = "1.1"
futures = "0.3"
sqlx = { version = "0.6.3", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1", features = ["full"] }
warp = "0.3.5"
warp-range = "2.0.0"
