[package]
name = "audio_streaming_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
warp = "0.3.5"
tokio = { version = "1", features = ["full"] }
hound = "3.4"
futures = "0.3"
bytes = "1.1"
# minimp3 = "0.5"
lame = "0.1"
