redis_uri: "redis://127.0.0.1:6379"
application:
  port: 8080
  host: 127.0.0.1
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "postgres"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
